# Generated by Django 2.0.8 on 2018-10-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20181011_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='result',
            name='game',
        ),
        migrations.RemoveField(
            model_name='result',
            name='team',
        ),
        migrations.RemoveField(
            model_name='score',
            name='game',
        ),
        migrations.RemoveField(
            model_name='score',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Player1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Player2',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
